on:
  push:
    branches:
      - prod

env:
  NODE_VERSION: '12.x'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, build, and deploy
      run: |
        npm install
        npm run build --prod 
        npm run deploy --token ${{ secrets.FIREBASE_TOKEN }}
